name:                sudoku
version:             0.1.0.0
description:         Suduko solver in Haskell.
license:             BSD3
author:              Nick Chapman
maintainer:          nic@amadido.co.uk
github:              Nick-Chapman/sudoku.git

dependencies:
- base >= 4.7 && < 5
- containers

default-extensions:
- LambdaCase
- NamedFieldPuns
- ScopedTypeVariables

ghc-options:
- -Werror
- -Wall
- -Wno-name-shadowing

library:
  source-dirs: src

executables:
  main.exe:
    main:                app/main.hs
    dependencies:        sudoku
